version: "3.3"

services:
  bot:
    image: "${BOT_IMAGE_NAME}"
    container_name: "${BOT_CONTAINER_NAME}"
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME}"
    volumes:
      - .:/usr/src/app/${BOT_NAME}
    command: python3 -m bot
    restart: unless-stopped
    env_file:
      - ".env"
    depends_on:
      - db
  db:
    image: postgres
    container_name: "${BOT_CONTAINER_NAME}_DB"
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - "${DATABASE_PORT}:5432"
    restart: unless-stopped
    logging:
      driver: none
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  cache:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}


networks:
  bot:
    driver: bridge

volumes:
  cache:
  db: